In [ ]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a[0]


1

In [ ]:
a[1]

2

In [ ]:
import time
import sys

In [ ]:
l=range(1000)
print(sys.getsizeof(5)*len(l))


28000


In [ ]:
array =np.arange(1000)
print(array.size*array.itemsize)

8000


In [155]:
SIZE =1000
l1=range(SIZE)
l2=range(SIZE)
a1=np.arange(SIZE)
a2=np.arange(SIZE)
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print ("python list took:",(time.time()-start)*1000) 
start = time.time()
result = a1+a2
print ("numpy took: ", (time.time()-start)*1000) 


python list took: 0.18310546875
numpy took:  0.1628398895263672


In [ ]:
a1 =np.array([1,2,3])
a2 =np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [ ]:
a1-a2


array([-3, -3, -3])

In [ ]:
a1*a2


array([ 4, 10, 18])

In [ ]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [ ]:
a=np.array([4,5,6])
a.ndim

1

In [ ]:
a.itemsize

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=np.array([[1,2],[3,4],[4,5]])
a.ndim

2

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a=np.array([[1,2],[3,4],[4,5]],dtype=np.float64)
a.itemsize

8

In [ ]:
a

array([[1., 2.],
       [3., 4.],
       [4., 5.]])

In [ ]:
a.size

6

In [ ]:
a.shape

(3, 2)

In [ ]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
l=range(5)
l

range(0, 5)

In [ ]:
l[0]

0

In [ ]:
l[1]

1

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
a          

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.min()

1

In [ ]:
a.max()

6

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([ 9, 12])

In [ ]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(a)

1.707825127659933

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a*b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
n=[6,7,8]
n [0:2]

[6, 7]

In [ ]:
n[-1]

8

In [125]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [126]:
a[1,2]

3

In [127]:
a[0:2,2]

array([8, 3])

In [128]:
a[-1]

array([9, 3, 2])

In [129]:
a[-1,0:2]

array([9, 3])

In [130]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [131]:
for row in a : 
  print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [132]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [133]:
a=np.arange(6).reshape(3,2)
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [134]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [135]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [136]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [137]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [138]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [139]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [140]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [141]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [142]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [143]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [145]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [146]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [147]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
for cell in a.flatten() :
  print (cell)


0
1
2
3
4
5
6
7
8
9
10
11


In [149]:
for x in np.nditer(a,order='C') :
  print (x)

0
1
2
3
4
5
6
7
8
9
10
11


In [150]:
for x in np.nditer(a,order='F') :
  print (x)

0
4
8
1
5
9
2
6
10
3
7
11


In [151]:
for x in np.nditer(a,order='F', flags= ['external_loop']) :
  print (x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [152]:
for x in np.nditer(a,op_flags= ['readwrite']) :
 x[...]= x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [153]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [154]:
for x,y in np.nditer([a,b]) :
  print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
